POST http://localhost:8080/api/v1/contents/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJuYW1lIiwiYXVkIjoiYXVkaWVuY2UiLCJzY29wZSI6ImNvbnRlbnQuY3JlYXRlIGNvbnRlbnQucHVibGlzaCBjb250ZW50LnJldmlldyIsImlzcyI6ImF1dGgwIiwiZXhwIjoxNTkwNzg0NTEyfQ.AT6cxO7MVwET8DmLDF_fmue0tCKCmqkq4ThAefE-QR1b0LaG7P7__NyHJNBVtAoZvtPium7w2JXBqoC3eSIeO90GV6_qhSzw0f4LgMI8GROyNerrVJDKnsDc2kbXUST74r15gHl8h32CjdYAWyU-Jm9vw4GY9vvu8cpAGEcETfO2OcgEGyepVxckh_kst2rPNitT1qvBZUa0i5kbBLcEkElte0fPusgBf9Ltv6wnaSqyMDl6fj_Ll4wzzjyUK9KlIYY7jK3J_6gsRirQjynmevjuw8DryVuMCaQcbeg5ppn38dYn2-RanbR3pi_bSPupqcfBTLqLPrHCkbPBp9FCo1Qd7f24rZaAJ_3L0H-UAtnu0kj3oM9789a3Kjqllel-tsGfc8GYUji3MUFKOxVKglyM134-t7pnlu0u0LQXtNaXpZHCowOyCPlZfpWrjSAZHZWKjhwmfYP8o_wiDGy-RrXB4-isbi4icGRJlYzIzrPrMfu9MuCJZfxopcL7xq21mxLtUVRraE3JgeSEeO3DE9jegMKC0wx6gMuGogqT2JAk46SP5ILOK7pOHJ6W7NtT6EO65YyBfaMENJzmauO--9HcwdS9KpFyPNUMVmClG0r8_1y14_7mM_fgPAx5EijPTiwjTyH3Ma2_Zt2l_Jd_tecVw2MhvNRe5BIDI7cW00g

{
  "path": "/",
  "title": "Home",
  "webType": {
    "Folder": {}
  },
  "description": "This is the root of the website",
  "text": "Empty",
  "theme": "default",
  "icon": "default.png"
}

###

POST http://localhost:8080/api/v1/contents/child
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJuYW1lIiwiYXVkIjoiYXVkaWVuY2UiLCJzY29wZSI6ImNvbnRlbnQuY3JlYXRlIGNvbnRlbnQucHVibGlzaCBjb250ZW50LnJldmlldyIsImlzcyI6ImF1dGgwIiwiZXhwIjoxNTkwOTI2NjE3fQ.FOP_CfYaFfQnijo4HIb3fySEC5fYLGpGVGhH_dfIQ0HbKU4QYjYHVH2ZBlWWuO7cDJsxQx8GISGRjs1OeIlIyOBoFfsscLGvkB9OPkX-f8dD4urhlC4czo47y486_pFWChh5WwIijwLjCYKYgEh-uDkybA4q37wJAvwsIqZxpUF8R7YfapFCJFv1Si5JENPIPX4V730BMuLq_7fZj-ijipFQcC_WWvfR28EBsgAOnBmhiOUgKCY0rnQKB2bbXGR1rznJfY2_KSFBbMv_YP8a48FJosOj10ANkYCZHK6aVhq_HD1BtKu_2ey83Hqg84qHodUtCF0DfgfCSB78gyUdAv27WFNlDZ9BbH3Br3qi3DUEMxg5Rc5v5T-fKDegIDJAFAUB9nGtd7yq9K6nf9mnrv60eyFbZdmtAw4yClBA3cPwP8nuIKZJhHETpYjKvs6oTGjcKmE-PIi-q8tPO-D7FX1KH5NjrdHhfdDRehZ-7ZLsMey9CgTiRzDDAudTQy_Ni4H_67LC87d-ONYSCU764Y2l4ho1htmV6ubpVlgh-X5fyLLdGgOI6IrkRRa2HOV0Koqky1-PF8W1jE-oDbLsK-JP3oHfpNsb6BOhqC1MuOFK-O4dK8m_IxKcboxZa2P9AOJCbphkJf3pywYU0siM8xJv7WNtrqScb1bfbPiGtoQ


{
  "path": "/child",
  "title": "Child",
  "webType": {
    "Page": {}
  },
  "description": "This is a child of the root page",
  "text": "Empty",
  "theme": "default",
  "icon": "default.png"
}

###

DELETE http://localhost:8080/api/v1/contents/child
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJuYW1lIiwiYXVkIjoiYXVkaWVuY2UiLCJzY29wZSI6ImNvbnRlbnQuY3JlYXRlIGNvbnRlbnQucHVibGlzaCBjb250ZW50LnJldmlldyIsImlzcyI6ImF1dGgwIiwiZXhwIjoxNTkwOTI2NjE3fQ.FOP_CfYaFfQnijo4HIb3fySEC5fYLGpGVGhH_dfIQ0HbKU4QYjYHVH2ZBlWWuO7cDJsxQx8GISGRjs1OeIlIyOBoFfsscLGvkB9OPkX-f8dD4urhlC4czo47y486_pFWChh5WwIijwLjCYKYgEh-uDkybA4q37wJAvwsIqZxpUF8R7YfapFCJFv1Si5JENPIPX4V730BMuLq_7fZj-ijipFQcC_WWvfR28EBsgAOnBmhiOUgKCY0rnQKB2bbXGR1rznJfY2_KSFBbMv_YP8a48FJosOj10ANkYCZHK6aVhq_HD1BtKu_2ey83Hqg84qHodUtCF0DfgfCSB78gyUdAv27WFNlDZ9BbH3Br3qi3DUEMxg5Rc5v5T-fKDegIDJAFAUB9nGtd7yq9K6nf9mnrv60eyFbZdmtAw4yClBA3cPwP8nuIKZJhHETpYjKvs6oTGjcKmE-PIi-q8tPO-D7FX1KH5NjrdHhfdDRehZ-7ZLsMey9CgTiRzDDAudTQy_Ni4H_67LC87d-ONYSCU764Y2l4ho1htmV6ubpVlgh-X5fyLLdGgOI6IrkRRa2HOV0Koqky1-PF8W1jE-oDbLsK-JP3oHfpNsb6BOhqC1MuOFK-O4dK8m_IxKcboxZa2P9AOJCbphkJf3pywYU0siM8xJv7WNtrqScb1bfbPiGtoQ

###

GET http://localhost:8080/api/v1/search?parent=/
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJuYW1lIiwiYXVkIjoiYXVkaWVuY2UiLCJzY29wZSI6ImNvbnRlbnQuY3JlYXRlIGNvbnRlbnQucHVibGlzaCBjb250ZW50LnJldmlldyIsImlzcyI6ImF1dGgwIiwiZXhwIjoxNTkwOTI2NjE3fQ.FOP_CfYaFfQnijo4HIb3fySEC5fYLGpGVGhH_dfIQ0HbKU4QYjYHVH2ZBlWWuO7cDJsxQx8GISGRjs1OeIlIyOBoFfsscLGvkB9OPkX-f8dD4urhlC4czo47y486_pFWChh5WwIijwLjCYKYgEh-uDkybA4q37wJAvwsIqZxpUF8R7YfapFCJFv1Si5JENPIPX4V730BMuLq_7fZj-ijipFQcC_WWvfR28EBsgAOnBmhiOUgKCY0rnQKB2bbXGR1rznJfY2_KSFBbMv_YP8a48FJosOj10ANkYCZHK6aVhq_HD1BtKu_2ey83Hqg84qHodUtCF0DfgfCSB78gyUdAv27WFNlDZ9BbH3Br3qi3DUEMxg5Rc5v5T-fKDegIDJAFAUB9nGtd7yq9K6nf9mnrv60eyFbZdmtAw4yClBA3cPwP8nuIKZJhHETpYjKvs6oTGjcKmE-PIi-q8tPO-D7FX1KH5NjrdHhfdDRehZ-7ZLsMey9CgTiRzDDAudTQy_Ni4H_67LC87d-ONYSCU764Y2l4ho1htmV6ubpVlgh-X5fyLLdGgOI6IrkRRa2HOV0Koqky1-PF8W1jE-oDbLsK-JP3oHfpNsb6BOhqC1MuOFK-O4dK8m_IxKcboxZa2P9AOJCbphkJf3pywYU0siM8xJv7WNtrqScb1bfbPiGtoQ
